version: '3.1'
services:

  postgresql:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./temp/data/db:/data/db
    environment:
      POSTGRES_DB: music-bot-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass


  be:
    image: node:18.12.0
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm install && DB_HOST=postgresql:5432 && npm run prod"
    ports:
      - "5000:5000"
    depends_on:
      - postgresql
